version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    env_file: .env
    container_name: postgres-service
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    env_file: .env
    container_name: spring-boot-app
    environment:
      SPRING_APPLICATION_JSON: '{
              "spring.datasource.url"  : "jdbc:postgresql://postgres:5432/$POSTGRES_DB",
              "spring.datasource.username" : "$POSTGRES_USER",
              "spring.datasource.password" : "$POSTGRES_PASSWORD",
              "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect",
              "spring.jpa.hibernate.ddl-auto" : "update"
            }'
    ports:
      - 8080:8080
    depends_on:
      - postgres
volumes:
  postgres_data:
